### ISSUE TITLE
create the obstacles and keep tracking scoring

### ISSUE THREAD

**Issue by Azizadx** [Azizadx/rs-flappy_brid#5]
- [x]  create the obstacle struct 
- [x]  render the obstacle
- [x]  crashing into to walls 
- [x] keep the score and the state of obstacle
